demo:
    wu: [your woffu endpoint]
    wk: [your woffu key]
    tk: [your trello key]
    ts: [your trello secret]
    tboard: [your trello board]
    wcid: [company or list]
    requests: [list of request types allowed]
prod:
    wu: [your woffu endpoint]
    wk: [your woffu key]
    tk: [your trello key]
    ts: [your trello secret]
    tboard: [your trello board]
    wcid: [company or list]
    requests: [list of request types allowed]    
